namespace: default
resources:
  - ../base
  - ../default/machine-deployment.yaml
  - ../../azure-cluster-identity

patchesStrategicMerge:
  - ../../azure-cluster-identity/azurecluster-identity-ref.yaml
  - patches/private-lb.yaml
  - patches/apiserver-host-dns.yaml
  - patches/azure-bastion.yaml

