namespace: capi-webhook-system

namePrefix: capz-

# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-azure"

resources:
  - ../../config/default/namespace.yaml
  - ../../config/default/aad-pod-identity-deployment.yaml
  - ../../config/crd
  - ../../config/webhook
  - ../../config/manager
  - ../../config/certmanager

patchesStrategicMerge:
  - ../../config/default/manager_image_patch.yaml
  - ../../config/default/manager_pull_policy.yaml
  - ../../config/default/manager_webhook_patch.yaml
  - ../../config/default/webhookcainjection_patch.yaml

vars:
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service

configurations:
  - ../../config/default/kustomizeconfig.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: capz-aad-pod-id-nmi-role
    path: patch_cluster_role.yaml
  - target:
      kind: Namespace
      name: system
      version: v1
    path: patch_namespace.yaml
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_service_account.yaml
  - target:
      group: apps
      kind: DaemonSet
      name: capz-nmi
      namespace: capi-webhook-system
      version: v1
    path: patch_service_account.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusteridentities.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepools.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepoolmachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: capz-aad-pod-id-nmi-binding
    path: patch_nmi_cluster_role_binding.yaml
